# Generated by Django 4.2.1 on 2023-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
