# Generated by Django 4.0 on 2024-02-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0007_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('payment_method', models.CharField(choices=[('MTN', 'MTN'), ('Card', 'Card'), ('Airtel', 'Airtel'), ('Cash', 'Cash')], default='MTN', max_length=200)),
                ('message', models.TextField(default='No recommendation about the products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('guest_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_orders', to='guest_user.guestorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_order_items', to='shops.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['-created_at'], name='guest_user__created_e29ad6_idx'),
        ),
    ]
