# Generated by Django 4.2.1 on 2023-08-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0007_alter_product_image'),
        ('guest_user', '0003_remove_guestcartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_numbe', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('payment_method', models.CharField(choices=[('MTN', 'MTN'), ('Card', 'Card'), ('Airtel', 'Airtel')], default='MTN', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('guest_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guest_user.guest_order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_order_items', to='shops.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='guest_order',
            index=models.Index(fields=['-created_at'], name='guest_user__created_a6a93c_idx'),
        ),
    ]
