# Generated by Django 4.2.1 on 2023-08-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_user', '0006_guestorder_message_alter_guestorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorderitem',
            name='guest_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_orders', to='guest_user.guestorder'),
        ),
    ]
