# Generated by Django 4.2.1 on 2023-06-22 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0005_product_order_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product_Order",
        ),
    ]
