# Generated by Django 4.2.1 on 2023-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_product_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviews',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default='reviewed'),
        ),
    ]
