# Generated by Django 4.2.1 on 2024-02-11 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_review_reviews_alter_review_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviews",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
