# Generated by Django 4.2.1 on 2023-07-05 04:19

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_delete_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shops.models.upload_to),
        ),
    ]
